/**
 * shared/services/auth/fsm/events.js
 * ---------------------------------------------------------------------------
 * Event constants. Single source of truth — every actor and every legacy-
 * bridge call site MUST reference these symbols, never raw strings.
 * ---------------------------------------------------------------------------
 */

export const E = Object.freeze({
  // Lifecycle
  BOOT: "BOOT",
  RESTORE_SESSION: "RESTORE_SESSION",

  // Firebase identity
  AUTH_CHANGED: "AUTH_CHANGED",
  REDIRECT_RESULT_RESOLVED: "REDIRECT_RESULT_RESOLVED",

  // User-initiated
  SIGN_IN_REQUESTED: "SIGN_IN_REQUESTED",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILED: "SIGN_IN_FAILED",
  SIGN_IN_CANCELLED: "SIGN_IN_CANCELLED",
  SIGN_OUT_REQUESTED: "SIGN_OUT_REQUESTED",
  SIGN_OUT_COMPLETED: "SIGN_OUT_COMPLETED",
  SIGN_OUT_FAILED: "SIGN_OUT_FAILED",

  // Setup / OTP / demo
  OTP_MODAL_SHOWN: "OTP_MODAL_SHOWN",
  OTP_VERIFIED: "OTP_VERIFIED",
  OTP_VERIFY_FAILED: "OTP_VERIFY_FAILED",
  SETUP_WIZARD_COMPLETED: "SETUP_WIZARD_COMPLETED",
  SETUP_WIZARD_SKIPPED: "SETUP_WIZARD_SKIPPED",
  DEMO_SETUP_STARTED: "DEMO_SETUP_STARTED",
  DEMO_SETUP_COMPLETED: "DEMO_SETUP_COMPLETED",

  // Backend resolutions
  USER_STATUS_RESOLVED: "USER_STATUS_RESOLVED",
  SETUP_STATUS_RESOLVED: "SETUP_STATUS_RESOLVED",
  PROFILE_CHECK_COMPLETED: "PROFILE_CHECK_COMPLETED",
  PROFILE_PICTURE_CHECK_COMPLETED: "PROFILE_PICTURE_CHECK_COMPLETED",

  // Lifecycle / connectivity
  FOREGROUND_RECHECK: "FOREGROUND_RECHECK",
  BACKGROUND_ENTERED: "BACKGROUND_ENTERED",
  NETWORK_ONLINE: "NETWORK_ONLINE",
  NETWORK_OFFLINE: "NETWORK_OFFLINE",
  CAPTIVE_PORTAL_DETECTED: "CAPTIVE_PORTAL_DETECTED",
  PERIODIC_STATUS_TICK: "PERIODIC_STATUS_TICK",

  // Account / permissions
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  ACCOUNT_RESTORED: "ACCOUNT_RESTORED",

  // Internal (machine-generated)
  SETUP_DELAY_ELAPSED: "@@SETUP_DELAY_ELAPSED",
  PICTURE_DELAY_ELAPSED: "@@PICTURE_DELAY_ELAPSED",
  SIGNOUT_SAFETY_ELAPSED: "@@SIGNOUT_SAFETY_ELAPSED",
  INTERNAL_ERROR: "@@INTERNAL_ERROR",
});
