/**
 * MarathonDashboard.jsx — Coach-facing Marathon Recognition dashboard.
 *
 * v5 enhancements:
 *  1. Team name and cycle dates auto-generated by backend
 *  2. Single-step LAP creation: pick 8 members, press Create
 *  3. No team name input, no date picker — all system-managed
 *  4. Fast participant loading via /api/marathon/participants
 *  5. LAP details view on tap (3×3 grid with live data)
 *  6. Swipe-left to delete LAP
 */
import React, { useEffect, useState, useCallback, useRef } from 'react';
import { useMarathon }      from '../hooks/useMarathon.js';
import MarathonShareSheet   from './MarathonShareSheet.jsx';
import { createMarathon, deleteMarathon, getMarathonParticipants, getCardData } from '../services/marathon.api.js';

// ── Constants ──────────────────────────────────────────────────────────────
const CARD_TYPES = [
  { type: 'team',       emoji: '👥', label: 'Team Card',   desc: 'Full 9-member grid' },
  { type: 'day_leader', emoji: '🌟', label: 'Day Leader',  desc: "Today's top performer" },
  { type: 'lap_leader', emoji: '👑', label: 'Lap Leader',  desc: 'Best this lap' },
];


const LAP_SIZE = 8; // members selected by coach (+ 1 auto-captain = 9 total)

// ── Date formatter ────────────────────────────────────────────────────────────
function formatLapDate(dateStr) {
  if (!dateStr) return '';
  const d = new Date(dateStr);
  if (isNaN(d.getTime())) return String(dateStr).substring(0, 10);
  return d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
}

// ── App theme tokens (matches App.js / Tailwind palette) ──────────────────
const T = {
  green:      '#16a34a',
  greenLight: '#dcfce7',
  greenBg:    '#f0fdf4',
  greenBorder:'#bbf7d0',
  red:        '#dc2626',
  redBg:      '#fef2f2',
  redBorder:  '#fecaca',
  gray50:     '#f9fafb',
  gray100:    '#f3f4f6',
  gray200:    '#e5e7eb',
  gray400:    '#9ca3af',
  gray600:    '#4b5563',
  gray800:    '#1f2937',
  white:      '#ffffff',
  blue:       '#0891b2',
  blueBg:     '#e0f2fe',
  purple:     '#7c3aed',
  purpleBg:   '#ede9fe',
};

// ── Load participant candidates via new fast endpoint ─────────────────────
async function loadParticipantCandidates(coachId) {
  const res  = await getMarathonParticipants({ coachId, role: 'coach' });
  const list = Array.isArray(res.data) ? res.data : [];
  // API returns { userId, name, photo, role, teamId, phone, isUpline }
  return list.map(m => ({
    userId:  m.userId,
    name:    m.name    || 'Member',
    photo:   m.photo   || null,
    phone:   m.phone   || '',
    teamId:  m.teamId  || '',
  }));
}

// ── Role validation ─────────────────────────────────────────────────────────
function validateRoles(participants) {
  const assistants = participants.filter(p => p.role === 'assistant_captain');
  if (assistants.length > 1) return 'Only 1 Asst. Captain allowed';
  return null;
}

// ── Avatar ──────────────────────────────────────────────────────────────────
const Avatar = ({ photo, name, size = 36 }) => (
  <div style={{
    width: size, height: size, borderRadius: '50%', flexShrink: 0,
    overflow: 'hidden', border: `1.5px solid ${T.gray200}`, background: T.gray100,
  }}>
    {photo ? (
      <img src={photo} alt={name} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
    ) : (
      <div style={{
        width: '100%', height: '100%', display: 'flex',
        alignItems: 'center', justifyContent: 'center',
        background: `linear-gradient(135deg, ${T.green}, #0891b2)`,
        fontSize: size * 0.38, fontWeight: 900, color: T.white,
      }}>
        {String(name || '?').charAt(0).toUpperCase()}
      </div>
    )}
  </div>
);

// ── Role badge chip ──────────────────────────────────────────────────────────
const RoleChip = ({ role, isUpline }) => {
  if (isUpline) {
    return (
      <span style={{
        fontSize: 10, fontWeight: 700, borderRadius: 4, padding: '1px 5px',
        background: T.purpleBg, color: T.purple,
      }}>Upline</span>
    );
  }
  if (role === 'coach') {
    return (
      <span style={{
        fontSize: 10, fontWeight: 700, borderRadius: 4, padding: '1px 5px',
        background: T.blueBg, color: T.blue,
      }}>Coach</span>
    );
  }
  return null;
};

// ── Participant row (picker) ────────────────────────────────────────────────
const ParticipantRow = ({ member, selected, lapRole, onToggle, onRoleChange, disabled }) => (
  <div
    onClick={() => !disabled && onToggle(member.userId)}
    style={{
      display: 'flex', alignItems: 'center', gap: 10,
      padding: '10px 12px', borderRadius: 10, marginBottom: 6,
      border: `1.5px solid ${selected ? T.green : T.gray200}`,
      background: selected ? T.greenBg : T.white,
      cursor: disabled && !selected ? 'not-allowed' : 'pointer',
      opacity: disabled && !selected ? 0.45 : 1,
    }}
  >
    <Avatar photo={member.photo} name={member.name} size={40} />
    <div style={{ flex: 1, minWidth: 0 }}>
      <div style={{
        fontSize: 13, fontWeight: 700, color: T.gray800,
        overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
      }}>
        {member.name}
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 4, marginTop: 2, flexWrap: 'wrap' }}>
        {member.teamId && (
          <span style={{ fontSize: 10, color: T.gray400 }}>#{member.teamId}</span>
        )}
        <RoleChip role={member.role} isUpline={member.isUpline} />
      </div>
    </div>
    
    <div style={{
      width: 22, height: 22, borderRadius: 6, flexShrink: 0,
      border: selected ? 'none' : `2px solid ${T.gray200}`,
      background: selected ? T.green : 'transparent',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
    }}>
      {selected && <span style={{ color: T.white, fontSize: 12, fontWeight: 900 }}>✓</span>}
    </div>
  </div>
);

// ── Create wizard ────────────────────────────────────────────────────────────
/**
 * Single-step LAP creation: coach picks 8 participants, presses Create.
 * Team name and cycle dates (startedAt, daysPerLap) are auto-generated by backend.
 */
const CreateMarathonWizard = ({ coachId, onCreated, onCancel }) => {
  const [members,      setMembers]      = useState([]);
  const [loadingMbrs,  setLoadingMbrs]  = useState(false);
  const [membersErr,   setMembersErr]   = useState(null);
const [selectedMembers, setSelectedMembers] = useState([]);
const [assistantCaptain, setAssistantCaptain] = useState(null);
const [step, setStep] = useState(1);
const selectedMemberObjects = members.filter(m =>
  selectedMembers.includes(m.userId)
);
  const [busy,         setBusy]         = useState(false);
  const [err,          setErr]          = useState(null);
  const [memberSearch, setMemberSearch] = useState('');

  const selectedIds = selectedMembers;
  const atMax        = selectedIds.length >= LAP_SIZE;

  // Load candidates on mount
  useEffect(() => {
    let cancelled = false;
    setLoadingMbrs(true); setMembersErr(null);
    loadParticipantCandidates(coachId)
      .then(list => { if (!cancelled) setMembers(list); })
      .catch(e  => { if (!cancelled) setMembersErr(e.message || 'Could not load members'); })
      .finally(() => { if (!cancelled) setLoadingMbrs(false); });
    return () => { cancelled = true; };
  }, [coachId]);

 const toggleMember = uid => {
   setErr(null);
  setSelectedMembers(prev => {
    if (prev.includes(uid)) {
      return prev.filter(id => id !== uid);
    }

    if (prev.length >= LAP_SIZE) {
      return prev;
    }

    return [...prev, uid];
  });
};

const validateParticipants = async () => {
  try {
    setErr(null);

    const participants = selectedMembers.map(id => ({
      userId: id,
      role: 'member'
    }));

    const result = await createMarathon({
      coachId,
      participants,
      role: 'coach',
      validateOnly: true
    });

    console.log('VALIDATION RESULT', result);

    if (result?.valid === false) {
      const count = result?.missingWeightIds?.length || 0;

      setErr(
        count > 0
          ? `${count} selected members have not logged their weight for the current marathon period.\n\nAsk them to upload their weight record first or remove them from the LAP.`
          : result?.message || 'Validation failed.'
      );

      return false;
    }

    return true;
  } catch (e) {
    console.error('VALIDATION ERROR', e);

    setErr(
      e?.response?.data?.message ||
      e?.message ||
      'Validation failed'
    );

    return false;
  }
};
  const handleCreate = async () => {
    if (selectedIds.length < LAP_SIZE) return setErr(`Select exactly ${LAP_SIZE} members (you + 8 = 9 total)`);
    if (selectedIds.length > LAP_SIZE) return setErr(`Too many — select exactly ${LAP_SIZE} members`);
    setBusy(true); setErr(null);
    try {
      // name, teamName, startedAt, daysPerLap, totalLaps are all auto-generated by backend
      const participants = selectedMembers.map(id => ({
  userId: id,
  role:
    id === assistantCaptain
      ? 'assistant_captain'
      : 'member'
}));

const result = await createMarathon({
  coachId,
  participants,
  role: 'coach'
});
      onCreated(result?.data?.marathonId || result?.data?.id || null);
    } catch (e) {
  console.error(e);

  const apiMessage =
    e?.response?.data?.message ||
    e?.message ||
    '';

  let userMessage =
    'Failed to create LAP. Please try again.';

  if (
    apiMessage.toLowerCase().includes('no weight record')
  ) {
    const countMatch = apiMessage.match(/^(\d+)/);

    const count = countMatch
      ? parseInt(countMatch[1], 10)
      : null;

    userMessage = count
      ? `${count} selected member${count > 1 ? 's have' : ' has'} not logged their weight for the current marathon period.\n\nAsk them to upload their weight record first or remove them from the LAP.`
      : `Some selected members have not logged their weight for the current marathon period.\n\nAsk them to upload their weight record first or remove them from the LAP.`;
  }

  setErr(userMessage);
} finally {
      setBusy(false);
    }
  };

  const remaining       = LAP_SIZE - selectedIds.length;
  const searchLower     = memberSearch.toLowerCase().trim();
  const filteredMembers = searchLower
    ? members.filter(m =>
        m.name.toLowerCase().includes(searchLower) ||
        String(m.teamId || '').includes(searchLower) ||
        String(m.phone  || '').includes(searchLower)
      )
    : members;

  return (
  <div style={{ textAlign: 'left' }}>

    {step === 1 && (
      <>
        {/* ===== STEP 1 : SELECT MEMBERS ===== */}

        <div style={{ display: 'flex', alignItems: 'center', marginBottom: 12 }}>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 15, fontWeight: 800, color: T.gray800 }}>
              New LAP — Pick 8 Members
            </div>

            <div style={{ fontSize: 11, color: T.gray400, marginTop: 1 }}>
              Team name & cycle dates are auto-assigned by the system.
            </div>
          </div>

          <span
            style={{
              fontSize: 12,
              fontWeight: 800,
              color: selectedIds.length === LAP_SIZE ? T.green : T.gray400,
              background:
                selectedIds.length === LAP_SIZE
                  ? T.greenLight
                  : T.gray100,
              borderRadius: 100,
              padding: '3px 10px',
            }}
          >
            {selectedIds.length}/{LAP_SIZE}
          </span>
        </div>

        <div
          style={{
            fontSize: 12,
            color: T.gray600,
            marginBottom: 10,
            background: T.greenBg,
            borderRadius: 8,
            padding: '8px 10px',
            border: `1px solid ${T.greenBorder}`,
          }}
        >
          You are auto-added as <strong>Captain</strong>.
          {remaining > 0
            ? ` Select ${remaining} more member${remaining > 1 ? 's' : ''}.`
            : ' All 8 selected — ready to continue!'}
        </div>

        {membersErr && (
          <div
            style={{
              background: T.redBg,
              border: `1px solid ${T.redBorder}`,
              borderRadius: 8,
              padding: '8px 12px',
              fontSize: 13,
              color: T.red,
              marginBottom: 10,
            }}
          >
            {membersErr}
          </div>
        )}

        <div style={{ position: 'relative', marginBottom: 8 }}>
          <input
            value={memberSearch}
            onChange={e => setMemberSearch(e.target.value)}
            placeholder="Search by name, mobile or team ID…"
            style={{
              width: '100%',
              boxSizing: 'border-box',
              padding: '10px',
              borderRadius: 8,
              border: `1px solid ${T.gray200}`,
            }}
          />
        </div>

        <div
          style={{
            maxHeight: '45vh',
            overflowY: 'auto',
            marginBottom: 12,
          }}
        >
          {filteredMembers.map(m => (
            <ParticipantRow
              key={m.userId}
              member={m}
              selected={selectedMembers.includes(m.userId)}
              onToggle={toggleMember}
              disabled={
                atMax &&
                !selectedMembers.includes(m.userId)
              }
            />
          ))}
        </div>

        {err && (
          <div
            style={{
              background: T.redBg,
              border: `1px solid ${T.redBorder}`,
              borderRadius: 8,
              padding: '8px 12px',
              fontSize: 13,
              color: T.red,
              marginBottom: 10,
            }}
          >
            {err}
          </div>
        )}

        <div
          style={{
            position: 'sticky',
            bottom: 0,
            background: '#fff',
            paddingTop: 12,
            borderTop: '1px solid #e5e7eb',
            display: 'flex',
            gap: 8,
          }}
        >
          <button
            onClick={onCancel}
            style={{ flex: 1 }}
          >
            Cancel
          </button>

         <button
  onClick={() => setStep(2)}
  disabled={
    selectedMembers.length !== LAP_SIZE
  }
  style={{ flex: 2 }}
>
  Next
</button>
        </div>
      </>
    )}

    {step === 2 && (
      <>
        {/* ===== STEP 2 : ASSISTANT CAPTAIN ===== */}

        <div
          style={{
            fontSize: 18,
            fontWeight: 700,
            marginBottom: 4,
          }}
        >
          Select Assistant Captain
        </div>

        <div
          style={{
            fontSize: 12,
            color: '#6b7280',
            marginBottom: 16,
          }}
        >
          Choose one member from the selected team.
        </div>

        <div
          style={{
            maxHeight: '55vh',
            overflowY: 'auto',
          }}
        >
          {selectedMemberObjects.map(member => (
            <div
              key={member.userId}
              onClick={() =>
                setAssistantCaptain(member.userId)
              }
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 12,
                padding: 12,
                borderRadius: 12,
                marginBottom: 8,
                cursor: 'pointer',
                border:
                  assistantCaptain === member.userId
                    ? '2px solid #16a34a'
                    : '1px solid #e5e7eb',
              }}
            >
              <input
                type="radio"
                checked={
                  assistantCaptain === member.userId
                }
                readOnly
              />

              <Avatar
                photo={member.photo}
                name={member.name}
                size={40}
              />

              <div>{member.name}</div>
            </div>
          ))}
        </div>

        <div
          style={{
            position: 'sticky',
            bottom: 0,
            background: '#fff',
            paddingTop: 12,
            borderTop: '1px solid #e5e7eb',
            display: 'flex',
            gap: 8,
          }}
        >
          <button
            onClick={() => setStep(1)}
            style={{ flex: 1 }}
          >
            Back
          </button>

          <button
            onClick={handleCreate}
            disabled={!assistantCaptain || busy}
            style={{ flex: 2 }}
          >
            {busy ? 'Creating...' : 'Create LAP'}
          </button>
        </div>
      </>
    )}

  </div>
);
};

// ── LAP list item — swipe-left to delete, tap to open details ─────────────
const LapListItem = ({ marathon, isSelected, onSelect, onOpenDetails, onDeleteSwipe, deleting }) => {
  const touchStartXRef = useRef(null);

  const handleTouchStart = (e) => {
    touchStartXRef.current = e.touches[0].clientX;
  };
  const handleTouchEnd = (e) => {
    if (touchStartXRef.current === null) return;
    const delta = e.changedTouches[0].clientX - touchStartXRef.current;
    touchStartXRef.current = null;
    if (delta < -60) {
      // swiped left ≥ 60px → trigger delete confirmation
      onDeleteSwipe(marathon.id);
    }
  };

  return (
    <div
      style={{
        display: 'flex', alignItems: 'flex-start', gap: 10,
        padding: '12px 14px',
        background: isSelected ? T.greenBg : T.white,
        border: `1.5px solid ${isSelected ? T.green : T.gray200}`,
        borderRadius: 12, marginBottom: 8,
        cursor: 'pointer',
        userSelect: 'none',
        opacity: deleting ? 0.5 : 1,
        transition: 'opacity 0.2s',
      }}
      onClick={() => { onSelect(marathon.id); onOpenDetails(marathon.id); }}
      onTouchStart={handleTouchStart}
      onTouchEnd={handleTouchEnd}
    >
      <div style={{
        width: 36, height: 36, borderRadius: 10, flexShrink: 0,
        background: isSelected ? T.green : T.gray100,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        fontSize: 16, marginTop: 2,
      }}>
        🏃
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{
          fontSize: 14, fontWeight: 700, color: T.gray800,
          overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
          lineHeight: 1.3,
        }}>
          {marathon.name}
        </div>
        <div style={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 5, marginTop: 4 }}>
          {marathon.lap_sequence && (
            <span style={{
              fontSize: 10, fontWeight: 800,
              color: isSelected ? T.green : T.gray600,
              background: isSelected ? T.greenLight : T.gray100,
              borderRadius: 4, padding: '1px 6px', lineHeight: 1.5,
            }}>LAP {marathon.lap_sequence}</span>
          )}
          <span style={{ fontSize: 11, color: T.gray400, lineHeight: 1.3 }}>
            {marathon.days_per_lap} days · {formatLapDate(marathon.started_at)}
          </span>
        </div>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0, paddingTop: 2 }}>
        {isSelected && (
          <span style={{
            fontSize: 10, fontWeight: 700, color: T.green,
            background: T.greenLight, borderRadius: 100, padding: '2px 8px',
            whiteSpace: 'nowrap',
          }}>Active</span>
        )}
        {/* No delete icon — use swipe left to delete */}
        <span style={{ fontSize: 18, color: T.gray400 }}>›</span>
      </div>
    </div>
  );
};

// ── Delete confirmation bottom sheet ─────────────────────────────────────────
const DeleteConfirmModal = ({ onConfirm, onCancel }) => (
  <div style={{
    position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.45)',
    display: 'flex', alignItems: 'flex-end', justifyContent: 'center',
    zIndex: 1000, padding: '0 0 env(safe-area-inset-bottom, 0)',
  }}
    onClick={onCancel}
  >
    <div
      onClick={e => e.stopPropagation()}
      style={{
        background: '#fff', borderRadius: '20px 20px 0 0',
        padding: '20px 20px calc(20px + env(safe-area-inset-bottom, 0))',
        width: '100%', maxWidth: 480, boxSizing: 'border-box',
      }}
    >
      <div style={{ fontSize: 16, fontWeight: 800, color: '#1f2937', marginBottom: 4 }}>
        Delete this LAP?
      </div>
      <div style={{ fontSize: 12, color: '#9ca3af', marginBottom: 4 }}>
        Tip: Swipe left on any LAP card to delete it.
      </div>
      <div style={{ fontSize: 13, color: '#6b7280', marginBottom: 20 }}>
        This will cancel the marathon permanently and cannot be undone.
      </div>
      <div style={{ display: 'flex', gap: 10 }}>
        <button onClick={onCancel} style={{
          flex: 1, padding: '12px', borderRadius: 10,
          border: '1.5px solid #e5e7eb', background: '#fff',
          fontSize: 14, fontWeight: 600, color: '#6b7280', cursor: 'pointer',
        }}>Cancel</button>
        <button onClick={onConfirm} style={{
          flex: 1, padding: '12px', borderRadius: 10,
          border: 'none', background: '#dc2626',
          fontSize: 14, fontWeight: 700, color: '#fff', cursor: 'pointer',
        }}>Delete LAP</button>
      </div>
    </div>
  </div>
);

// ── LAP Details Modal ─────────────────────────────────────────────────────────
const DISCIPLINE_STATUS_MAP = {
  eligible:  { icon: '🟢', label: 'Submitted', color: '#059669' },
  missed:    { icon: '🔴', label: 'Missed',    color: '#dc2626' },
  no_upload: { icon: '🟡', label: 'Pending',   color: '#ca8a04' },
};

const ROLE_BADGE_MAP = {
  captain:           { label: 'C',  bg: '#059669', color: '#fff' },
  assistant_captain: { label: 'AC', bg: '#0891b2', color: '#fff' },
};

const DetailCell = ({ member }) => {
  const {
    name, profileImage, role, isAssistantCaptainDownline,
    dailyGrams, dailyWeightChange, dayChange, lapGrams, disciplineStatus,
    isDayLeader, isLapLeader,
  } = member;
  const ds = DISCIPLINE_STATUS_MAP[disciplineStatus] || DISCIPLINE_STATUS_MAP.no_upload;
  const rb = ROLE_BADGE_MAP[role] || null;

  // Defensive fallback: dailyGrams → dailyWeightChange → dayChange → lapGrams (vs. baseline).
  // lapGrams ensures a value is shown when prevClosingWeight is null (Day 1 / missed yesterday).
  const grams = dailyGrams != null
    ? dailyGrams
    : dailyWeightChange != null
    ? Math.round(dailyWeightChange * 1000)
    : dayChange != null
    ? Math.round(dayChange * 1000)
    : lapGrams != null
    ? lapGrams
    : null;
  const isLoss = grams != null && grams < 0;
  const isGain = grams != null && grams > 0;
  // <1000g: show as grams; ≥1000g: convert to kg (2dp)
  const gramsDisplay = grams == null ? '—'
    : grams === 0 ? '0g'
    : (() => {
        const abs  = Math.abs(grams);
        const sign = grams < 0 ? '-' : '+';
        return abs >= 1000 ? `${sign}${(abs / 1000).toFixed(2)} kg` : `${sign}${abs}g`;
      })();

  const ringColor = isDayLeader ? '#f59e0b' : isLapLeader ? '#2563eb' : '#e5e7eb';
  const ringWidth = isDayLeader || isLapLeader ? 2.5 : 2;

  return (
    <div style={{
      background: '#fff', border: '1px solid #e5e7eb', borderRadius: 14,
      padding: '8px 6px 10px', display: 'flex', flexDirection: 'column',
      alignItems: 'center', gap: 4, position: 'relative',
      boxShadow: isDayLeader
        ? '0 0 0 2px rgba(245,158,11,0.35)'
        : isLapLeader ? '0 0 0 2px rgba(37,99,235,0.30)' : 'none',
    }}>
      {/* Top-left: role badge (C/AC) — or plain ⭐ for AC-downline members */}
      {rb ? (
        <div style={{
          position: 'absolute', top: 4, left: 4, zIndex: 5,
          background: rb.bg, color: rb.color,
          fontSize: 9, fontWeight: 800, borderRadius: 4, padding: '1px 4px',
        }}>{rb.label}</div>
      ) : isAssistantCaptainDownline ? (
        <div style={{
          position: 'absolute', top: 2, left: 4, zIndex: 5, fontSize: 11, lineHeight: 1,
        }}>⭐</div>
      ) : null}

      {/* Top-right: leader badge */}
      {isDayLeader && (
        <div style={{
          position: 'absolute', top: 4, right: 4, zIndex: 5,
          background: '#f59e0b', borderRadius: '50%', width: 20, height: 20,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          boxShadow: '0 2px 6px rgba(245,158,11,0.7)', fontSize: 11, lineHeight: 1,
        }}>👑</div>
      )}
      {isLapLeader && !isDayLeader && (
        <div style={{
          position: 'absolute', top: 4, right: 4, zIndex: 5,
          background: '#2563eb', borderRadius: '50%', width: 20, height: 20,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          boxShadow: '0 2px 6px rgba(37,99,235,0.7)', fontSize: 11, lineHeight: 1,
        }}>👕</div>
      )}

      <div style={{
        width: 52, height: 52, borderRadius: '50%',
        overflow: 'hidden', border: `${ringWidth}px solid ${ringColor}`,
        background: '#f3f4f6', flexShrink: 0,
      }}>
        {profileImage ? (
          <img src={profileImage} alt={name} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
        ) : (
          <div style={{
            width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center',
            background: 'linear-gradient(135deg,#059669,#0891b2)',
            fontSize: 20, fontWeight: 900, color: '#fff',
          }}>{String(name || '?').charAt(0).toUpperCase()}</div>
        )}
      </div>
      <div style={{
        fontSize: 10, fontWeight: 700, color: '#111827', textAlign: 'center',
        width: '100%', padding: '0 4px', boxSizing: 'border-box',
        overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
      }}>{name}</div>
      <span style={{
        fontSize: 11, fontWeight: 800, borderRadius: 6, padding: '2px 6px',
        background: isLoss ? '#dcfce7' : isGain ? '#fef3c7' : '#f3f4f6',
        color:      isLoss ? '#15803d' : isGain ? '#92400e' : '#6b7280',
      }}>{gramsDisplay}</span>
      <div style={{ fontSize: 10, color: ds.color, fontWeight: 600 }}>
        {ds.icon} {ds.label}
      </div>
    </div>
  );
};

const LapDetailsModal = ({ marathonId, coachId: cId, marathonName, onClose }) => {
  const [data,    setData]    = useState(null);
  const [loading, setLoading] = useState(true);
  const [err,     setErr]     = useState(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true); setErr(null);
    getCardData({ marathonId, cardType: 'team', coachId: cId })
      .then(res => { if (!cancelled) setData(res.data); })
      .catch(e  => { if (!cancelled) setErr(e.message || 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [marathonId, cId]);

  const participants = data?.participants || [];
  const slots = [...participants];
  while (slots.length < 9) slots.push(null);
  const grid = [slots.slice(0, 3), slots.slice(3, 6), slots.slice(6, 9)];

  const teamTotal   = data?.teamDailyTotalDisplay || '—';
  const isLossTotal = data?.teamDailyTotal != null && data.teamDailyTotal < 0;
  const isGainTotal = data?.teamDailyTotal != null && data.teamDailyTotal > 0;

  return (
    <div
      style={{
        position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.55)',
        display: 'flex', alignItems: 'flex-end', justifyContent: 'center',
        zIndex: 1000,
      }}
      onClick={onClose}
    >
      <div
        onClick={e => e.stopPropagation()}
        style={{
          background: '#f9fafb', borderRadius: '20px 20px 0 0',
          width: '100%', maxWidth: 480, boxSizing: 'border-box',
          maxHeight: '90vh', overflowY: 'auto',
          padding: '0 0 calc(12px + env(safe-area-inset-bottom, 0))',
        }}
      >
        {/* Handle */}
        <div style={{ display: 'flex', justifyContent: 'center', padding: '12px 0 4px' }}>
          <div style={{ width: 40, height: 4, borderRadius: 2, background: '#e5e7eb' }} />
        </div>
        {/* Header */}
        <div style={{
          background: 'linear-gradient(135deg,#0f766e,#0891b2)',
          padding: '14px 16px 12px', color: '#fff', margin: '0 12px 12px',
          borderRadius: 16,
        }}>
          <div style={{ fontSize: 15, fontWeight: 800, marginBottom: 2 }}>
            {data?.marathonName || marathonName}
          </div>
          {data && (
            <div style={{ fontSize: 11, opacity: 0.85 }}>
              Lap {data.lapNumber}  ·  Day {data.dayNumber}
            </div>
          )}
        </div>

        {loading && (
          <div style={{ textAlign: 'center', padding: '24px 0', color: T.gray400, fontSize: 14 }}>
            Loading participants…
          </div>
        )}
        {err && (
          <div style={{ margin: '0 12px', background: T.redBg, borderRadius: 12,
            padding: '10px 14px', fontSize: 13, color: T.red }}>
            {err}
          </div>
        )}
        {!loading && !err && (
          <div style={{ padding: '0 12px' }}>
            {grid.map((row, ri) => (
              <div key={ri} style={{ display: 'flex', gap: 8, marginBottom: ri < 2 ? 8 : 0 }}>
                {row.map((m, ci) => (
                  m ? (
                    <div key={m.userId} style={{ flex: 1 }}>
                      <DetailCell member={m} />
                    </div>
                  ) : (
                    <div key={`e${ri}${ci}`} style={{
                      flex: 1, borderRadius: 14, border: '1px dashed #e5e7eb',
                      background: '#fafafa', minHeight: 120,
                    }} />
                  )
                ))}
              </div>
            ))}
            <div style={{
              marginTop: 12, background: '#fff', borderRadius: 12,
              border: '1px solid #f3f4f6',
              padding: '10px 16px',
              display: 'flex', justifyContent: 'space-between', alignItems: 'center',
            }}>
              <span style={{ fontSize: 12, color: '#6b7280', fontWeight: 600 }}>Team total today</span>
              <span style={{
                fontSize: 16, fontWeight: 900,
                color: isLossTotal ? '#059669' : isGainTotal ? '#d97706' : '#6b7280',
              }}>{teamTotal}</span>
            </div>
          </div>
        )}

        <button
          onClick={onClose}
          style={{
            display: 'block', width: 'calc(100% - 24px)', margin: '12px 12px 0',
            padding: '12px', borderRadius: 10, border: 'none',
            background: T.gray100, fontSize: 14, fontWeight: 600,
            color: T.gray600, cursor: 'pointer',
          }}
        >Close</button>
      </div>
    </div>
  );
};

// ── Main dashboard ────────────────────────────────────────────────────────────
const MarathonDashboard = ({ coachId }) => {
  const {
    marathons, loadingList, listError, fetchMarathons, removeMarathon,
    cardData, shareUrl, loadingCard, cardError, shareOpen,
    generateCard, closeShare,
  } = useMarathon({ coachId });

  const [selectedId,      setSelectedId]      = useState('');
  const [activeCardType,  setActiveCardType]  = useState(null);
  const [showCreate,      setShowCreate]      = useState(false);
  const [deletingId,      setDeletingId]      = useState(null);
  const [confirmDeleteId, setConfirmDeleteId] = useState(null);
  const [deleteError,     setDeleteError]     = useState(null);
  const [lapSearch,       setLapSearch]       = useState('');
  const [detailsMarathonId, setDetailsMarathonId] = useState(null);

  useEffect(() => { fetchMarathons('active'); }, [fetchMarathons]);

  useEffect(() => {
    if (marathons.length > 0 && !selectedId) {
      setSelectedId(String(marathons[0].id));
    }
  }, [marathons, selectedId]);

  const handleCreated = (newMarathonId) => {
    setShowCreate(false);
    if (newMarathonId) setSelectedId(String(newMarathonId));
    fetchMarathons('active');
  };

  const handleDeleteConfirmed = async () => {
    const id = confirmDeleteId;
    setConfirmDeleteId(null);
    setDeleteError(null);
    setDeletingId(id);
    removeMarathon(Number(id));
    if (String(selectedId) === String(id)) setSelectedId('');
    try {
      await deleteMarathon({ marathonId: id, coachId });
      await fetchMarathons('active');
    } catch (e) {
      setDeleteError(e.message || 'Failed to delete LAP. Please try again.');
      await fetchMarathons('active');
    } finally {
      setDeletingId(null);
    }
  };

  const handleCardTap = type => {
    if (loadingCard || !selectedId) return;
    setActiveCardType(type);
    generateCard({ marathonId: Number(selectedId), cardType: type });
  };

  const handleOpenDetails = (id) => {
    setDetailsMarathonId(id);
  };

  // existingTeams: deduplicated team names from current marathon list
  const existingTeams = [...new Set(marathons.map(m => m.team_name).filter(Boolean))];

  const filteredMarathons = lapSearch.trim()
    ? marathons.filter(m => m.name.toLowerCase().includes(lapSearch.toLowerCase().trim()))
    : marathons;

  const detailsMarathon = detailsMarathonId
    ? marathons.find(m => String(m.id) === String(detailsMarathonId))
    : null;

  return (
    <div style={{
      padding: 'max(12px, env(safe-area-inset-top, 12px)) max(16px, env(safe-area-inset-right, 16px)) calc(40px + env(safe-area-inset-bottom, 0px)) max(16px, env(safe-area-inset-left, 16px))',
      maxWidth: 480, margin: '0 auto', boxSizing: 'border-box',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    }}>

      <div style={{ marginBottom: 16 }}>
        <h1 style={{ fontSize: 20, fontWeight: 800, color: T.gray800, margin: 0 }}>
          Marathon LAPs
        </h1>
        <p style={{ fontSize: 13, color: T.gray400, margin: '2px 0 0' }}>
          Tap a LAP to view details · swipe left to delete
        </p>
      </div>

      {deleteError && (
        <div style={{
          background: T.redBg, border: `1px solid ${T.redBorder}`,
          borderRadius: 8, padding: '8px 12px', fontSize: 13, color: T.red, marginBottom: 12,
          display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8,
        }}>
          <span>{deleteError}</span>
          <button onClick={() => setDeleteError(null)} style={{
            background: 'none', border: 'none', cursor: 'pointer',
            color: T.red, fontSize: 16, fontWeight: 700, lineHeight: 1, padding: 0,
          }}>✕</button>
        </div>
      )}

      {listError && (
        <div style={{ background: T.redBg, border: `1px solid ${T.redBorder}`,
          borderRadius: 8, padding: '8px 12px', fontSize: 13, color: T.red, marginBottom: 12 }}>
          {listError}
        </div>
      )}

      {loadingList && (
        <div style={{ textAlign: 'center', padding: '24px 0', color: T.gray400, fontSize: 14 }}>
          Loading…
        </div>
      )}

      {!loadingList && marathons.length > 0 && (
        <div style={{ marginBottom: 20 }}>
          <div style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            marginBottom: 8,
          }}>
            <div style={{ fontSize: 11, fontWeight: 700, color: T.gray400,
              textTransform: 'uppercase', letterSpacing: 1 }}>
              Your LAPs ({marathons.length})
            </div>
          </div>

          {marathons.length > 3 && (
            <div style={{ position: 'relative', marginBottom: 10 }}>
              <span style={{
                position: 'absolute', left: 10, top: '50%', transform: 'translateY(-50%)',
                fontSize: 14, color: T.gray400, pointerEvents: 'none',
              }}>🔍</span>
              <input
                value={lapSearch}
                onChange={e => setLapSearch(e.target.value)}
                placeholder="Search LAPs…"
                style={{
                  width: '100%', boxSizing: 'border-box',
                  padding: '9px 32px 9px 32px', borderRadius: 10,
                  border: `1.5px solid ${lapSearch ? T.green : T.gray200}`,
                  fontSize: 13, outline: 'none', fontFamily: 'inherit',
                  background: T.white,
                }}
              />
              {lapSearch && (
                <button onClick={() => setLapSearch('')} style={{
                  position: 'absolute', right: 8, top: '50%', transform: 'translateY(-50%)',
                  background: 'none', border: 'none', cursor: 'pointer',
                  color: T.gray400, fontSize: 14, padding: '2px 4px',
                }}>✕</button>
              )}
            </div>
          )}

          {filteredMarathons.length === 0 && lapSearch && (
            <div style={{ textAlign: 'center', color: T.gray400, fontSize: 13, padding: '12px 0' }}>
              No LAPs matching "{lapSearch}"
            </div>
          )}

          {filteredMarathons.map(m => (
            <LapListItem
              key={m.id}
              marathon={m}
              isSelected={String(selectedId) === String(m.id)}
              onSelect={id => setSelectedId(String(id))}
              onOpenDetails={handleOpenDetails}
              onDeleteSwipe={id => setConfirmDeleteId(id)}
              deleting={deletingId === m.id}
            />
          ))}
        </div>
      )}

      {!loadingList && !showCreate && marathons.length === 0 && (
        <div style={{
          textAlign: 'center', padding: '32px 20px',
          background: T.gray50, borderRadius: 16,
          border: `1.5px dashed ${T.gray200}`, marginBottom: 16,
        }}>
          <div style={{ fontSize: 36, marginBottom: 8 }}>🏁</div>
          <div style={{ fontSize: 14, color: T.gray600, marginBottom: 16 }}>
            No active LAPs. Create your first one.
          </div>
        </div>
      )}

      {showCreate ? (
        <div style={{
          background: T.white, border: `1.5px solid ${T.gray200}`,
          borderRadius: 16, padding: '16px',
        }}>
          <CreateMarathonWizard
            coachId={coachId}
            onCreated={handleCreated}
            onCancel={() => setShowCreate(false)}
          />
        </div>
      ) : (
        <button
          onClick={() => setShowCreate(true)}
          style={{
            width: '100%', padding: '12px', borderRadius: 10,
            background: T.green, color: T.white,
            fontSize: 14, fontWeight: 700, border: 'none',
            cursor: 'pointer', marginBottom: 20,
            boxShadow: '0 2px 8px rgba(22,163,74,0.25)',
          }}
        >
          + New LAP
        </button>
      )}

      {selectedId && !showCreate && (
        <div>
          <div style={{ fontSize: 11, fontWeight: 700, color: T.gray400,
            textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8 }}>
            Generate &amp; Share
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {CARD_TYPES.map(({ type, emoji, label, desc }) => {
              const isActive  = activeCardType === type;
              const isLoading = isActive && loadingCard;
              return (
                <button
                  key={type}
                  onClick={() => handleCardTap(type)}
                  disabled={loadingCard}
                  style={{
                    display: 'flex', alignItems: 'center', gap: 12,
                    padding: '14px 16px', borderRadius: 12, textAlign: 'left',
                    border: `1.5px solid ${isActive ? T.green : T.gray200}`,
                    background: isActive ? T.greenBg : T.white,
                    cursor: loadingCard ? 'not-allowed' : 'pointer',
                    opacity: loadingCard && !isActive ? 0.6 : 1,
                  }}
                >
                  <span style={{ fontSize: 24, flexShrink: 0 }}>{emoji}</span>
                  <span style={{ flex: 1 }}>
                    <span style={{ display: 'block', fontSize: 14, fontWeight: 700, color: T.gray800 }}>
                      {label}
                    </span>
                    <span style={{ fontSize: 12, color: T.gray400 }}>{desc}</span>
                  </span>
                  <span style={{ fontSize: 18, color: isLoading ? T.green : T.gray400 }}>
                    {isLoading ? '⏳' : '›'}
                  </span>
                </button>
              );
            })}
          </div>
          {cardError && (
            <div style={{ background: T.redBg, border: `1px solid ${T.redBorder}`,
              borderRadius: 8, padding: '8px 12px', fontSize: 13, color: T.red, marginTop: 10 }}>
              {cardError}
            </div>
          )}
        </div>
      )}

      <MarathonShareSheet isOpen={shareOpen} onClose={closeShare} card={cardData} shareUrl={shareUrl} />

      {confirmDeleteId && (
        <DeleteConfirmModal
          onConfirm={handleDeleteConfirmed}
          onCancel={() => setConfirmDeleteId(null)}
        />
      )}

      {detailsMarathonId && (
        <LapDetailsModal
          marathonId={detailsMarathonId}
          coachId={coachId}
          marathonName={detailsMarathon?.name || ''}
          onClose={() => setDetailsMarathonId(null)}
        />
      )}
    </div>
  );
};

export default MarathonDashboard;
